# fly.toml app configuration file generated for promethium-network-discord-bot on 2023-08-23T01:46:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "promethium-network-discord-bot"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
